[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_2022_kashe = "8jDR5qcFspA1kydVnLRpSguWgWTg7rGBrGfovoKg7c7N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
add-liquidity = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g add liquidity"
airdrop = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g Airdrop to admin wallet"
buy = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g buy"
create-pool = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g create pool"
is-initialized = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g Is initialized!"
mint = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g token-mint"
remove-liquidity = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g remove liquidity"
sell = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g sell"
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false
