[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_2022_pumpfun = "HjUotZMTaso8hy6kbXATt43gQZW1v3B3mgkWwcwRXmkD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
is-initialized = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g Is initialized!"
add-liquidity = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g add liquidity"
airdrop = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g Airdrop to admin wallet"
buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g buy"
create-pool = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g create pool"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g token-mint"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g "
sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g sell"
remove-liquidity = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g remove liquidity"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false
