[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_2022_kashe = "AkQWMDTiZbTbNTXhMFqxN9eoMrW3zE1biTCk2HE5Cmyb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"
