[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
token_2022_kashe = "97emQnUDtp5uoCjyCQMZpfhpRhffHHymAgVBnLreJDkF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"
