[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
token_2022_kashe = "8x1nUf7tuDe1c8jh51ptBMt5YQENk5ddpvqQVekA6afW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"
