[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
token_2022_kashe = "ARtRTjoKQpaZBTyqXBEMkUwb1EWrqoBKaF9TzjLH3NdQ"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"
