[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_2022_kashe = "7vzCaeRXLYPayXqzMcVYp88DzwwJdN4GhodAEpvqUuzd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
add-liquidity = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g add liquidity"
airdrop = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g Airdrop to admin wallet"
buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g buy"
create-pool = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g create pool"
is-initialized = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g Is initialized!"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g token-mint"
sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g sell"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g "

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false
