[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
token_2022_kashe = "A75Rd9gwDREAjGUCYN3cpPM9faLbmm7iWu6trMP84URk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
