[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_2022_pumpfun = "DKzDDvhAd8L4uatXE6ykYPFdVWknqgE2LuBFMGZUoMEZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
create-pool = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g create pool"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g token-mint"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g "
add-liquidity = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g add liquidity"
buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g buy"
airdrop = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g Airdrop to admin wallet"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false
